model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan_vit.VQModel
  params:
    image_size: 64
    patch_size: 8
    encoder:
          dim: 768
          depth: 8
          heads: 12
          mlp_dim: 3072
          channels: 3
    decoder:
          dim: 768
          depth: 8
          heads: 12
          mlp_dim: 3072
          channels : 3
    quantizer:
          embed_dim: 32
          n_embed: 4096 #8192
          beta: 0.25

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    #batch_size: 1
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain_crop 
      params:
          image_folder: image_folder: /root/VQGanomaly-ResNet-CareNet-Vit/breast_dataset/train
          size: 1024

    validation:
      target: taming.data.custom.CustomTest_crop
      params:
          image_folder:  /root/VQGanomaly-ResNet-CareNet-Vit/breast_dataset/val
          size: 1024
