model:
  base_learning_rate: 2.0e-06
  target: taming.models.diffusion.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema
    unet_config:
      target: taming.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: taming.models.diffusion.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    #batch_size: 1
    num_workers: 0
    train:
      target: taming.data.custom.CustomTrain_crop_latent #taming.data.custom.CustomTrain
      params:
          image_folder: /scratch/coolsa/datasets/mvtec_anomaly/screw/train/good
      #   #training_images_list_file: some/training.txt
          size: 1024
      #   training_images_list_file: /home/aurelie/THESE/VQGanoDIP_benchmark/train_zipper.txt #/home/aurelie/THESE/VQGanoDIP_benchmark/zipper_crop_train.txt #C:/Users/arb/vqganodip_benchmark/train_PCBA_new_272.txt
      #   size: 256 #1024
    validation:
      target: taming.data.custom.CustomTest_crop_latent
      params:
          image_folder: /scratch/coolsa/datasets/mvtec_anomaly/screw/val
        #test_images_list_file: some/test.txt
          size: 1024
        # test_images_list_file: /home/aurelie/THESE/VQGanoDIP_benchmark/train_zipper.txt #/home/aurelie/THESE/VQGanoDIP_benchmark/zipper_crop_valid.txt
        # size: 256 #1024

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True