model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan_vit.VQModel
  params:
    image_size: 64
    patch_size: 8
    encoder:
          dim: 768
          depth: 12
          heads: 12
          mlp_dim: 3072
          channels: 3
    decoder:
          dim: 768
          depth: 12
          heads: 12
          mlp_dim: 3072
          channels : 3
    quantizer:
          embed_dim: 32
          n_embed: 8192
          beta: 0.25

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    #batch_size: 1
    num_workers: 0
    train:
      target: taming.data.custom.CustomTrain_crop #taming.data.custom.CustomTrain
      params:
          image_folder: /scratch/coolsa/datasets/mvtec_anomaly/screw/train/good
      #   #training_images_list_file: some/training.txt
          size: 1024
      #   training_images_list_file: /home/aurelie/THESE/VQGanoDIP_benchmark/train_zipper.txt #/home/aurelie/THESE/VQGanoDIP_benchmark/zipper_crop_train.txt #C:/Users/arb/vqganodip_benchmark/train_PCBA_new_272.txt
      #   size: 256 #1024
    validation:
      target: taming.data.custom.CustomTest_crop
      params:
          image_folder: /scratch/coolsa/datasets/mvtec_anomaly/screw/val
        #test_images_list_file: some/test.txt
          size: 1024
        # test_images_list_file: /home/aurelie/THESE/VQGanoDIP_benchmark/train_zipper.txt #/home/aurelie/THESE/VQGanoDIP_benchmark/zipper_crop_valid.txt
        # size: 256 #1024


trainer:
  accelerator: 'gpu'
  devices: 2
    